### ISSUE TITLE
Correcciones

### ISSUE THREAD

**Issue by jrsg** [UniversidadCristobalColon/pw2-e1-Arzival#1]
Utiliza la etiqueta h2 pues en un subencabezado
https://github.com/UniversidadCristobalColon/pw2-e1-Arzival/blob/6ea9356820b514cc1628309983758e6c215bf305/ejer1.html#L14

Utiliza h3
https://github.com/UniversidadCristobalColon/pw2-e1-Arzival/blob/6ea9356820b514cc1628309983758e6c215bf305/ejer1.html#L16

Cada estrofa es un párrafo.

https://github.com/UniversidadCristobalColon/pw2-e1-Arzival/blob/6ea9356820b514cc1628309983758e6c215bf305/ejer1.html#L18

**Comment by Arzival** [comment]
Corregido
